package com.cross.plateform.common.rpc.core.codec.impl;

import com.cross.plateform.common.rpc.core.codec.CommonRpcEncoder;
import com.google.protobuf.Message;

public class ProtocolBufEncoder implements CommonRpcEncoder {

	@Override
	public byte[] encode(Object object) throws Exception {
		if (!(object instanceof Message)) {
			throw new Exception("Send object is not type of com.google.protobuf.Message,pls sure the object is generated by pb,object is: " + object);
		}
		Message message = (Message) object;
		return message.toByteArray();
	}

}
